#!/usr/bin/env python

import sys
import os

def main():
	print "+----------------------------+"
	print "| Welcome to RecruiterReview |"
	print "+----------------------------+"
	print " Please select what you would like me to do:"
	print " - Enter 1 to merge separate activity reports from the same period of time"
	print " - Enter 2 to get the review for an activity report"
	print " - Enter 3 to do 1 and 2"
	while True:
		command = raw_input(' I choose: ')
		if command.isdigit() == 1:
			if (int(command) >= 1) and (int(command) <=3):
				break
		print " Please choose and enter 1, 2, or 3"
	if int(command) == 1:
		print " Please enter all files you would like to merge (separate with spaces)."
		files = raw_input(' Files: ')
		os.system("./ListMerge " + files)
	elif int(command) == 2:
		print " Please enter activity report file."
		activityReport = raw_input(' File: ')
		print " "
		print " ... "
		print " "
		os.system("./GetReview " + activityReport)
	else: # does not handle ListMerge failing
		print " Please enter all files you would like to merge (separate with spaces)."
		files = raw_input(' Files: ')
		os.system("./ListMerge " + files)

		filename = raw_input(' Merged filename: ')
		print " "
		print " ... "
		print " "
		os.system("./GetReview " + filename)




# Standard boilerplate to call the main() function to begin
# the program.
if __name__ == '__main__':
	main()
