#!/usr/bin/env python

import sys
import csv
import os

def main():

	# checks correct number of arguments
	if len(sys.argv) < 3:
		print "ALERT: Usage Error - Please run with at least two files."
		return 0
	indexFiles = len(sys.argv) 
	for x in range (1, indexFiles):
		if sys.argv[x].endswith('.csv') == 0:
			print "ALERT: Usage Error - Incorrect file type. Please include csv files ONLY."
			return 0
	#print "Please confirm that all files have these categories in this order:"
	#print "Name | Activity | Candidate | Job | Creation time"
	#while True:
	#	confirm  = raw_input('Y/N:')
	#	if confirm == "Y" or confirm == "N":
	#		break
	#	else:
	#		print 'Please enter "Y"or "N"'
	#if confirm == "N":
	#	print "Please use files that only have the correct categories in the correct order."
	#	return 0
	#elif confirm != "Y":
	#	return 0
	print " Please enter name of final merged file using the format activity_report_YYYY-MM-DD_YYYY-MM-DD.csv"
	while True:
		filename = raw_input(' Filename: ')
		test = filename.split("_")
		if len(test) == 4 and test[0] == "activity" and test[1] == "report":
			initSplit = test[3].split(".")
			if len(initSplit) == 2 and initSplit[1] == "csv":
				fSplit = test[2].split("-")
				sSplit = initSplit[0].split("-")
				if len(fSplit) == 3 and len(sSplit) == 3:
					counter = 0
					if fSplit[0].isdigit() and len(fSplit[0]) == 4 and sSplit[0].isdigit() and len(sSplit[0]) == 4:
						for x in range (1,3):
							if fSplit[x].isdigit() and len(fSplit[x]) == 2:
								counter += 1
							if sSplit[x].isdigit() and len(sSplit[x]) == 2:
								counter +=1
						if counter == 4:
							break
		else:
			sys.exit(" Please make sure to follow the format guidelines.")

	with open(filename, 'w') as csvOutput:
		writer = csv.writer(csvOutput) # merged list will end up here
		writer.writerow(['Name', 'Activity', 'Candidate', 'Job', 'Creation time'])
		for x in range (1, indexFiles):
			with open (sys.argv[x], 'r') as csvInput:
				reader = csv.reader(csvInput)
				header = next(reader) # getting rid of header
				if checkCategories(header) == 0:
					os.remove(filename)
					return 0
				for row in reader:
					writer.writerow(row)
	sys.exit(" Merge Success!")

# checks that activity report has expected categories
def checkCategories(header):

	with open('header.csv', 'r') as toMatch:
		match = csv.reader(toMatch)
		correctHeader = next(match)
	if header != correctHeader:
		print "ALERT: Usage Error - Please only use files with these categories in this order:"
		print "Name | Activity | Candidate | Job | Creation time" # have it read from header
		return 0
	return 1

# Standard boilerplate to call the main() function to begin
# the program.
if __name__ == '__main__':
	main()
